name: Build Zen Browser

on:
  workflow_call:
    inputs:
      from_ci:
        type: boolean
        required: false
        default: true
      VERSION:
        type: string
        required: true

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --privileged

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependency
        run: |
          pacman -Syuu --noconfirm --needed base-devel git clang llvm lld rust bc python npm nodejs \
          diffutils yasm nasm mesa imake xorg-server-xvfb jack libpulse alsa-lib \
          cbindgen dump_syms wasi-compiler-rt wasi-libc wasi-libc++ wasi-libc++abi \
          pciutils inetutils jq rsync sccache unzip zip \
          mime-types dbus-glib nss ttf-font

      - name: Build x86_64-v3
        env:
          PKGVER: ${{ inputs.VERSION }}
        run: |
          sed -i "s/\(_pkgver=\"\)[^\"]*\"/\1$PKGVER\"/" PKGBUILD
          bash build.sh

      - name: Get Release Description
        id: description
        run: |
          echo -e $(curl -s https://api.github.com/repos/zen-browser/desktop/releases/latest | jq -r '.body') > build.md
          DELIM="$(openssl rand -hex 8)"
          echo "BUILD_LOG<<${DELIM}" >> "$GITHUB_OUTPUT"
          cat build.md >> "$GITHUB_OUTPUT"
          echo "${DELIM}" >> "$GITHUB_OUTPUT"

      - name: Get Tag
        id: build_tag
        run: |
          TAG="v${{ inputs.VERSION }}"
          echo "BUILD_TAG=$TAG" >> $GITHUB_OUTPUT

      - name: Upload To Release
        uses: svenstaro/upload-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: /out/packages/zen*.pkg*.zst
          release_name: Zen Browser Arch Package Release
          body: ${{ steps.description.outputs.BUILD_LOG }}
          tag: ${{ steps.build_tag.outputs.BUILD_TAG }}
          file_glob: true

  update:
    permissions: write-all
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Bump Tag
        env:
          PKGVER: ${{ inputs.VERSION }}
        run: sed -i "s/\(_pkgver=\"\)[^\"]*\"/\1$PKGVER\"/" PKGBUILD

      - name: Commit latest tag
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          skip_checkout: true
          file_pattern: 'PKGBUILD'
          commit_message: 'Zen: v${{ inputs.VERSION }}'
